# Generated by Django 4.2.3 on 2023-07-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название концепта')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'концепт',
                'verbose_name_plural': 'концепты',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название узла')),
                ('type', models.CharField(choices=[('KN', 'Понятие (знаю)'), ('UN', 'Закономерность (понимаю)'), ('CS', 'Кейс (наблюдаю)'), ('SK', 'Навык (умею)')], default='KN', max_length=2, verbose_name='тип узла')),
                ('testability', models.BooleanField(default=True, verbose_name='Проверяемая?')),
                ('concept', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.concept', verbose_name='Концепт')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'вершина графа',
                'verbose_name_plural': 'вершины графа',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='graph.node', verbose_name='...к вершине')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='graph.node', verbose_name='От вершины...')),
            ],
            options={
                'verbose_name': 'ребро в графе',
                'verbose_name_plural': 'ребра в графе',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
