# Generated by Django 4.2.3 on 2023-07-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Концепт')),
            ],
            options={
                'verbose_name': 'концепт',
                'verbose_name_plural': 'концепты',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('KN', 'Понятие'), ('UN', 'Закономерность'), ('CS', 'Кейс'), ('SK', 'Навык')], default='KN', max_length=2, verbose_name='тип узла')),
            ],
            options={
                'verbose_name': 'тип узла',
                'verbose_name_plural': 'типы узлов',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('testability', models.BooleanField(default=True)),
                ('concept', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.concept')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.type')),
            ],
            options={
                'verbose_name': 'узел графа',
                'verbose_name_plural': 'узлы графа',
            },
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='graph.node')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='graph.node')),
            ],
            options={
                'verbose_name': 'ребро в графе',
                'verbose_name_plural': 'ребро в графе',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
