# Generated by Django 4.2.3 on 2023-07-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название концепта'),
        ),
    ]
