# Generated by Django 4.2.3 on 2023-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_concept_is_active_concept_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('KN', 'Понятие'), ('UN', 'Закономерность'), ('CS', 'Кейс'), ('SK', 'Навык')], default='KN', max_length=2, verbose_name='тип узла'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
