# Generated by Django 4.2.3 on 2023-07-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_node_type_delete_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'вершина графа', 'verbose_name_plural': 'вершины графа'},
        ),
        migrations.AlterModelOptions(
            name='noderelation',
            options={'verbose_name': 'ребро в графе', 'verbose_name_plural': 'ребра в графе'},
        ),
        migrations.AlterField(
            model_name='node',
            name='concept',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.concept', verbose_name='Концепт'),
        ),
        migrations.AlterField(
            model_name='node',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='node',
            name='testability',
            field=models.BooleanField(default=True, verbose_name='Проверяемая?'),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название узла'),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('KN', 'Понятие (знаю)'), ('UN', 'Закономерность (понимаю)'), ('CS', 'Кейс (наблюдаю)'), ('SK', 'Навык (умею)')], default='KN', max_length=2, verbose_name='тип узла'),
        ),
        migrations.AlterField(
            model_name='noderelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='graph.node', verbose_name='...к вершине'),
        ),
        migrations.AlterField(
            model_name='noderelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='graph.node', verbose_name='От вершины...'),
        ),
    ]
