version: '3.9'

services:   
  # Django application
  web:
    # Папка, из которой берется Dockerfile
    build: ./server
   
    # Build commands
    command: sh -c "gunicorn conf.wsgi:application --bind 0.0.0.0:8000"
    
    # Storage volumes
    volumes:
      # сервер будет перезагружаться при изменениях в коде
      - ./server/:/code/
      # статика будет храниться и вне контейнера
      - ./data/static:/code/static
      - ./data/media:/code/media
     
    # Exposing port 8000
    ports:
      - "8000:8000"

    restart: "on-failure"

    depends_on:
      - db

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    env_file:
      - ./.env.dev
  
  db:
    image: postgres
    # файлы базы хранятся снаружи контейнера
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: