# Generated by Django 4.2.3 on 2023-07-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название экзамена')),
            ],
            options={
                'verbose_name': 'экзамен',
                'verbose_name_plural': 'экзамены',
            },
        ),
        migrations.CreateModel(
            name='NumTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок группы тем экзамена')),
            ],
            options={
                'verbose_name': 'заголовок группы тем экзамена',
                'verbose_name_plural': 'заголовки групп тем экзамена',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема задачи')),
            ],
            options={
                'verbose_name': 'тема задачи',
                'verbose_name_plural': 'темы задач',
            },
        ),
        migrations.CreateModel(
            name='TrainerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер задачи в кодификаторе')),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.exam')),
                ('num_title', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.numtitle')),
                ('subject', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.theme')),
            ],
            options={
                'verbose_name': 'указатель для задачи на рубрикатор',
                'verbose_name_plural': 'указатели для задач на рубрикатор',
            },
        ),
    ]
