# Generated by Django 4.2.3 on 2023-07-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'вид экзамена', 'verbose_name_plural': 'виды экзаменов'},
        ),
        migrations.CreateModel(
            name='SubjectExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.subject')),
            ],
            options={
                'verbose_name': 'экзамен по предмету',
                'verbose_name_plural': 'экзамены по предметам',
            },
        ),
    ]
