# Generated by Django 4.2.3 on 2023-07-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_alter_node_options_alter_noderelation_options_and_more'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '1. экзамен', 'verbose_name_plural': '1. экзамены'},
        ),
        migrations.AlterModelOptions(
            name='numtitle',
            options={'verbose_name': '2. заголовок для номера из экзамена', 'verbose_name_plural': '2. заголовки для номеров из экзамена'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': '3. тема задачи', 'verbose_name_plural': '3. темы задач'},
        ),
        migrations.AlterModelOptions(
            name='trainertag',
            options={'verbose_name': '4. указатель на рубрикатор', 'verbose_name_plural': '4. указатели на рубрикатор'},
        ),
        migrations.AlterField(
            model_name='trainertag',
            name='exam',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='trainertag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Тег отображается?'),
        ),
        migrations.AlterField(
            model_name='trainertag',
            name='num_title',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainer.numtitle', verbose_name='Название номера'),
        ),
        migrations.AlterField(
            model_name='trainertag',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='graph.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='trainertag',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.theme', verbose_name='Название темы'),
        ),
    ]
