# Generated by Django 4.2.3 on 2023-07-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_exam_options_subjectexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectExamNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(verbose_name='Номер задания')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.subjectexam')),
            ],
            options={
                'verbose_name': 'номер в экзамене по предмету',
                'verbose_name_plural': 'номера в экзамене по предметам',
            },
        ),
    ]
