# Generated by Django 4.2.3 on 2023-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_subjectexamnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectexamnumber',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
