# Generated by Django 4.2.3 on 2023-07-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_rename_theme_examtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtheme',
            name='subject_exam_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.subjectexamnumber'),
        ),
    ]
