# Generated by Django 4.2.3 on 2023-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_examtheme_subject_exam_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtheme',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Тег отображается?'),
        ),
    ]
