# Generated by Django 4.2.3 on 2023-07-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_remove_trainertag_exam_remove_trainertag_num_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtag',
            options={'verbose_name': 'привязка к кодификатору', 'verbose_name_plural': 'привязки к кодификатору'},
        ),
    ]
