# Generated by Django 4.2.3 on 2023-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_exam_is_active_alter_subjectexam_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectexam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
    ]
