# Generated by Django 4.2.3 on 2023-07-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_subjectexamnumber_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtag',
            options={'verbose_name': 'тема из кодификатора', 'verbose_name_plural': 'темы из кодификатора'},
        ),
        migrations.AlterModelOptions(
            name='subjectexamnumber',
            options={'verbose_name': 'номер в экзамене', 'verbose_name_plural': 'номера в экзамене'},
        ),
    ]
