# Generated by Django 4.2.3 on 2023-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telegram_id_alter_user_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_of',
            field=models.CharField(choices=[('parent', 'Родитель'), ('old', 'Выпускник'), ('2024', '11 класс'), ('2025', '10 класс'), ('2026', '9 класс'), ('2027', '8 класс'), ('2028', '7 класс')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
