# Generated by Django 4.2.3 on 2023-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_class_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_of',
            field=models.CharField(blank=True, choices=[('parent', 'Родитель'), ('old', 'Выпускник'), ('2024', '11 класс'), ('2025', '10 класс'), ('2026', '9 класс'), ('2027', '8 класс'), ('2028', '7 класс')], max_length=10),
        ),
    ]
