# Generated by Django 5.2.5 on 2025-08-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0002_alter_concept_options_alter_node_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название лекции')),
                ('content', models.TextField(help_text='Используйте редактор для добавления текста, изображений и формул', verbose_name='Содержание лекции')),
                ('vk_video_url', models.URLField(blank=True, help_text='Вставьте ссылку на видео с VK (например: https://vk.com/video-123456_789012)', verbose_name='Ссылка на видео VK')),
                ('vk_video_title', models.CharField(blank=True, max_length=200, verbose_name='Название видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.concept', verbose_name='Привязанный концепт')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.node', verbose_name='Привязанный узел')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
                'ordering': ['order', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('concept__isnull', True), ('node__isnull', False)), models.Q(('concept__isnull', False), ('node__isnull', True)), _connector='OR'), name='lecture_single_entity')],
            },
        ),
    ]
