# Generated by Django 5.2.5 on 2025-08-31 14:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=tinymce.models.HTMLField(help_text='Используйте редактор для добавления текста, изображений и формул', verbose_name='Содержание лекции'),
        ),
    ]
