# Generated by Django 5.2.5 on 2025-08-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['title'], 'verbose_name': 'концепт', 'verbose_name_plural': 'концепты'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['title'], 'verbose_name': 'вершина графа', 'verbose_name_plural': 'вершины графа'},
        ),
        migrations.AlterModelOptions(
            name='noderelation',
            options={'ordering': ['parent__title', 'child__title'], 'verbose_name': 'ребро в графе', 'verbose_name_plural': 'ребра в графе'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
    ]
