# Generated by Django 5.2.5 on 2025-08-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0002_alter_concept_options_alter_node_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название задачи')),
                ('condition', models.TextField(verbose_name='Условие задачи')),
                ('solution', models.TextField(blank=True, verbose_name='Разбор задачи')),
                ('question_type', models.CharField(choices=[('STRING', 'Ответ строкой'), ('NUMBER', 'Ответ числом'), ('SEQ_ORDERED', 'Последовательность с порядком'), ('SEQ_UNORDERED', 'Последовательность без порядка')], default='STRING', max_length=20, verbose_name='Тип задания')),
                ('max_score', models.PositiveIntegerField(default=1, verbose_name='Максимальный балл')),
                ('grading_policy', models.CharField(choices=[('ALL_OR_NOTHING', 'Все или ничего'), ('PER_ERROR', 'За каждую ошибку -1 балл')], default='ALL_OR_NOTHING', max_length=20, verbose_name='Политика проверки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('precision', models.PositiveIntegerField(default=0, verbose_name='Точность (количество знаков после запятой)')),
                ('analogs', models.ManyToManyField(blank=True, to='questions.question', verbose_name='Аналогичные задачи')),
                ('nodes', models.ManyToManyField(blank=True, to='graph.node', verbose_name='Связанные узлы графа')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответов',
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
