# Generated by Django 5.2.5 on 2025-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название задачи (опционально)'),
        ),
    ]
