# Generated by Django 5.2.5 on 2025-08-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_title'),
    ]

    operations = [
    ]
