# Generated by Django 5.2.5 on 2025-08-24 17:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='condition',
            field=tinymce.models.HTMLField(verbose_name='Условие задачи'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Разбор задачи'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст варианта'),
        ),
    ]
