# Generated by Django 5.2.5 on 2025-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0003_auto_20250824_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_topics',
            field=models.ManyToManyField(blank=True, to='exams.examtopic', verbose_name='Подтемы экзаменов'),
        ),
    ]
