# Generated by Django 5.2.5 on 2025-08-31 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0002_alter_concept_options_alter_node_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название экзамена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'тип экзамена',
                'verbose_name_plural': 'типы экзаменов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.subject', verbose_name='Предмет')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examsubjects', to='exams.examtype', verbose_name='Тип экзамена')),
            ],
            options={
                'verbose_name': 'предмет экзамена',
                'verbose_name_plural': 'предметы экзаменов',
                'ordering': ['order', 'subject__title'],
                'unique_together': {('exam_type', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер задания')),
                ('title', models.CharField(max_length=300, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examnumbers', to='exams.examsubject', verbose_name='Предмет экзамена')),
            ],
            options={
                'verbose_name': 'номер задания',
                'verbose_name_plural': 'номера заданий',
                'ordering': ['order', 'number'],
                'unique_together': {('exam_subject', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExamTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название подтемы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('exam_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtopics', to='exams.examnumber', verbose_name='Номер задания')),
            ],
            options={
                'verbose_name': 'подтема экзамена',
                'verbose_name_plural': 'подтемы экзаменов',
                'ordering': ['order', 'title'],
            },
        ),
    ]
