# Generated by Django 4.2.3 on 2023-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Id в телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username в Telegram'),
        ),
    ]
