# Generated by Django 4.2.3 on 2023-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_alter_node_options_alter_noderelation_options_and_more'),
        ('trainer', '0002_alter_exam_options_alter_numtitle_options_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='graph.node', verbose_name='Вершины графа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trainer_tag',
            field=models.ManyToManyField(blank=True, to='trainer.trainertag', verbose_name='Экзаменационный тег'),
        ),
    ]
