# Generated by Django 4.2.3 on 2023-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Обычная проверка строки'), (2, 'Набор символов в строгом порядке'), (3, 'Набор символов в случайном порядке'), (4, 'Выбор одного верного ответа (с кнопками)'), (5, 'Выбор нескольких вариантов ответа (с кнопками)'), (6, 'Развернутый ответ текстом или картинкой')], default=1, verbose_name='Тип задания'),
        ),
    ]
