# Generated by Django 4.2.3 on 2023-07-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_subject_exam_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject_exam_number',
            new_name='subject_exam_numbers',
        ),
    ]
