# Generated by Django 4.2.3 on 2023-07-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_rename_examtheme_examtag'),
        ('questions', '0004_rename_subject_exam_number_question_subject_exam_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_exam_numbers',
        ),
        migrations.AddField(
            model_name='question',
            name='exam_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.examtag', verbose_name='Тег экзамена (new)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trainer_tags',
            field=models.ManyToManyField(blank=True, to='trainer.trainertag', verbose_name='Экзаменационный тег (old)'),
        ),
    ]
