# Generated by Django 4.2.3 on 2023-07-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_alter_examtag_options_and_more'),
        ('questions', '0006_alter_question_exam_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='trainer.examtag', verbose_name='Тег экзамена (new)'),
        ),
    ]
