# Generated by Django 4.2.3 on 2023-07-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_exam_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trainer_tags',
        ),
    ]
