# Generated by Django 4.2.3 on 2023-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_question_trainer_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'verbose_name': 'вариант ответа', 'verbose_name_plural': 'варианты ответа'},
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Обычная проверка строки'), (7, 'Проверка числа'), (2, 'Набор символов в строгом порядке'), (3, 'Набор символов в случайном порядке'), (4, 'Выбор одного верного ответа (с кнопками)'), (5, 'Выбор нескольких вариантов ответа (с кнопками)'), (6, 'Развернутый ответ текстом или картинкой')], default=1, verbose_name='Тип задания'),
        ),
    ]
