# Generated by Django 4.2.3 on 2023-07-30 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_questionoption_options_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_new',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
