# Generated by Django 4.2.3 on 2023-08-02 13:29

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_question_text_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_new',
            field=ckeditor.fields.RichTextField(verbose_name='Текст вопроса'),
        ),
    ]
