# Generated by Django 4.2.3 on 2023-08-02 13:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_images_alter_question_question_text_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_new',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст вопроса'),
        ),
    ]
