# Generated by Django 4.2.3 on 2023-08-08 06:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_remove_question_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_text_new',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Комментарий (пояснение) к вопросу'),
            preserve_default=False,
        ),
    ]
