# Generated by Django 4.2.3 on 2023-08-11 10:51

import apps.questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_explanation_text_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.questions.models.get_question_image_directory_path, verbose_name='Картинка для телеграма'),
        ),
    ]
